--vim =require '/home/qiumix/.local/share/bob/nightly/share/nvim/runtime/lua/vim/_core/shared.lua'
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
require 'functions'
require 'config'
require 'plugins'
