vim.pack.add({ { src = "https://github.com/zuqini/zpack.nvim" } })
require("core.options")
require("core.autocmd")
require("core.usercmd")
require("zpack").setup()
require("core.lsp")
vim.cmd(":colorscheme gruvbox")
