vim.pack.add({
  {
    src = gh("nvim-treesitter/nvim-treesitter"),
    version = "main",
  },
  {
    src = gh("nvim-treesitter/nvim-treesitter-textobjects"),
    version = "main",
  },
  { src = gh('nvim-lua/plenary.nvim') },
  { src = gh('MunifTanjim/nui.nvim') },
  { src = gh('rcarriga/nvim-notify') },
  { src = gh('wakatime/vim-wakatime') },
  { src = gh('rachartier/tiny-inline-diagnostic.nvim') },
  { src = gh('tris203/precognition.nvim') },
  { src = gh('nvzone/showkeys') },
  { src = gh('numToStr/FTerm.nvim') },
  { src = gh('neovim/nvim-lspconfig') },
  { src = gh('folke/noice.nvim') },
  { src = gh('windwp/nvim-autopairs') },
  { src = gh('saecki/crates.nvim') },
  { src = gh('mikesmithgh/kitty-scrollback.nvim') },
  { src = gh('ibhagwan/fzf-lua') },
  { src = gh("MeanderingProgrammer/render-markdown.nvim") },
  { src = gh("iamcco/markdown-preview.nvim") },
  { src = gh('SilverofLight/kd_translate.nvim') },
  { src = gh('sitiom/nvim-numbertoggle') },
  { src = gh("echasnovski/mini.nvim") },
  { src = gh("stevearc/conform.nvim") },
  { src = gh("xiyaowong/transparent.nvim") },
  { src = gh("lewis6991/gitsigns.nvim") },
  { src = gh("sindrets/diffview.nvim") },
  { src = gh("folke/lazydev.nvim") },
  {
    src = gh("saghen/blink.cmp"),
    version = vim.version.range("^1"),
  },
  {
    src = gh('mikavilpas/yazi.nvim'),
    version = vim.version.range('*')
  },
  { src = gh('goolord/alpha-nvim') },
  { src = gh("folke/which-key.nvim") },
  { src = gh("gbprod/yanky.nvim") },
})
