---@type wk.Spec
return {
  -- <leader>w Prefix & Ctrl-w Helpers
  {
    "<C-h>",
    "<C-w>h",
    desc = "Go to Left Window",
    mode = "n",
    remap = true,
    icon = { icon = "󰅁 ", color = "cyan" },
  },
  {
    "<C-j>",
    "<C-w>j",
    desc = "Go to Lower Window",
    mode = "n",
    remap = true,
    icon = { icon = "󰜮 ", color = "cyan" },
  },
  {
    "<C-k>",
    "<C-w>k",
    desc = "Go to Upper Window",
    mode = "n",
    remap = true,
    icon = { icon = "󰜷 ", color = "cyan" },
  },
  {
    "<C-l>",
    "<C-w>l",
    desc = "Go to Right Window",
    mode = "n",
    remap = true,
    icon = { icon = "󰅂 ", color = "cyan" },
  },
  {
    "<C-S-Up>",
    "<cmd>resize +5<CR>",
    desc = "Resize window up",
    mode = "n",
    silent = true,
    icon = { icon = "󰜷 ", color = "grey" },
  },
  {
    "<C-S-Down>",
    "<cmd>resize -5<CR>",
    desc = "Resize window down",
    mode = "n",
    silent = true,
    icon = { icon = "󰜮 ", color = "grey" },
  },
  {
    "<C-S-Left>",
    "<cmd>vertical resize -5<CR>",
    desc = "Resize window left",
    mode = "n",
    silent = true,
    icon = { icon = "󰅁 ", color = "grey" },
  },
  {
    "<C-S-Right>",
    "<cmd>vertical resize +5<CR>",
    desc = "Resize window right",
    mode = "n",
    silent = true,
    icon = { icon = "󰅂 ", color = "grey" },
  },
  {
    "<leader>ww",
    "<C-W>p",
    desc = "Other Window",
    mode = "n",
    remap = true,
    icon = { icon = "󰅁 ", color = "cyan" },
  },
  {
    "<leader>wd",
    "<C-W>c",
    desc = "Delete Window",
    mode = "n",
    remap = true,
    icon = { icon = "󰭌 ", color = "red" },
  },
  {
    "<leader>w-",
    "<C-W>s",
    desc = "Split Window Below",
    mode = "n",
    remap = true,
    icon = { icon = "󰖰 ", color = "cyan" },
  },
  {
    "<leader>w|",
    "<C-W>v",
    desc = "Split Window Vertically",
    mode = "n",
    remap = true,
    icon = { icon = "| ", color = "cyan" },
  },
}
