require('plugins.install')

only_require_without_vsc('plugins.blink')
only_require_without_vsc('plugins.conform')
only_require_without_vsc('plugins.git')
only_require_without_vsc('plugins.treesitter')
only_require_without_vsc('plugins.whichkey')
require('plugins.yanky')
require('plugins.mini')
require('plugins.lastplace')
only_require_without_vsc('plugins.lazydev')
only_require_without_vsc('plugins.tiny')
local crates = only_require_without_vsc('crates')
if crates then
  crates.setup()
end
require('kitty-scrollback').setup()
require('plugins.fterm')
require('plugins.flash')
only_require_without_vsc('plugins.whichkey')
only_require_without_vsc('plugins.colorscheme')
only_require_without_vsc('plugins.marks')
only_require_without_vsc('plugins.telescope')
only_require_without_vsc('plugins.rime')
only_require_without_vsc('plugins.sqlua')
only_require_without_vsc('plugins.snack')
only_require_without_vsc('plugins.ui')
only_require_without_vsc('plugins.showkeys')
only_require_without_vsc('plugins.ai')
only_require_without_vsc('plugins.neoscroll')
only_require_without_vsc('plugins.markdown')
only_require_without_vsc('plugins.rust')
