require('plugins.install')

only_require_without_vsc('plugins.blink')
only_require_without_vsc('plugins.conform')
only_require_without_vsc('plugins.git')
only_require_without_vsc('plugins.markdown')
only_require_without_vsc('plugins.typst')
only_require_without_vsc('plugins.treesitter')
only_require_without_vsc('plugins.whichkey')
only_require_without_vsc('plugins.ui')
require('plugins.yanky')
require('plugins.mini')
only_require_without_vsc('plugins.lazydev')
only_require_without_vsc('plugins.tiny')
local crates = only_require_without_vsc('crates')
if crates then
  crates.setup()
end
require('kitty-scrollback').setup()
require('plugins.fterm')
only_require_without_vsc('plugins.whichkey')
only_require_without_vsc('plugins.colorscheme')
only_require_without_vsc('plugins.marks')
only_require_without_vsc('plugins.telescope')
only_require_without_vsc('plugins.rime')
only_require_without_vsc('plugins.sqlua')
only_require_without_vsc('plugins.snack')
