return {
	sources = {
		files = {
			hidden = true,
			ignored = true,
			win = {
				input = {
					keys = {
						["<S-h>"] = "toggle_hidden",
						["<S-i>"] = "toggle_ignored",
						["<S-f>"] = "toggle_follow",
						["<C-y>"] = { "yazi_copy_relative_path", mode = { "n", "i" } },
					},
				},
			},
			exclude = {
				"**/.git/*",
				"**/node_modules/*",
				"**/.yarn/cache/*",
				"**/.yarn/install*",
				"**/.yarn/releases/*",
				"**/.pnpm-store/*",
				"**/.idea/*",
				"**/.DS_Store",
				"build/*",
				"coverage/*",
				"dist/*",
				"hodor-types/*",
				"**/target/*",
				"**/public/*",
				"**/digest*.txt",
				"**/.node-gyp/**",
				"**/claude/debug",
				"**/claude/file-history",
				"**/claude/plans",
				"**/claude/plugins",
				"**/claude/projects",
				"**/claude/session-env",
				"**/claude/shell-snapshots",
				"**/claude/statsig",
				"**/claude/telemetry",
				"**/claude/todos",
				"**/claude/history.jsonl",
			},
		},
		grep = {
			hidden = true,
			ignored = true,
			win = {
				input = {
					keys = {
						["<S-h>"] = "toggle_hidden",
						["<S-i>"] = "toggle_ignored",
						["<S-f>"] = "toggle_follow",
					},
				},
			},
			exclude = {
				"**/.git/*",
				"**/node_modules/*",
				"**/.yarn/cache/*",
				"**/.yarn/install*",
				"**/.yarn/releases/*",
				"**/.pnpm-store/*",
				"**/.venv/*",
				"**/.idea/*",
				"**/.DS_Store",
				"**/yarn.lock",
				"build*/*",
				"coverage/*",
				"dist/*",
				"certificates/*",
				"hodor-types/*",
				"**/target/*",
				"**/public/*",
				"**/digest*.txt",
				"**/.node-gyp/**",
				"**/claude/debug",
				"**/claude/file-history",
				"**/claude/plans",
				"**/claude/plugins",
				"**/claude/projects",
				"**/claude/session-env",
				"**/claude/shell-snapshots",
				"**/claude/statsig",
				"**/claude/telemetry",
				"**/claude/todos",
				"**/claude/history.jsonl",
			},
		},
		grep_buffers = {},
		explorer = {
			hidden = true,
			ignored = true,
			supports_live = true,
			auto_close = true,
			diagnostics = true,
			diagnostics_open = false,
			focus = "list",
			follow_file = true,
			git_status = true,
			git_status_open = false,
			git_untracked = true,
			jump = { close = true },
			tree = true,
			watch = true,
			exclude = {
				".git",
				".yarn/cache/**",
				".yarn/install/**",
				".yarn/install*",
				".yarn/releases/**",
				".pnpm-store",
				".venv",
				".DS_Store",
				"**/.node-gyp/**",
				"**/claude/debug",
				"**/claude/file-history",
				"**/claude/plans",
				"**/claude/plugins",
				"**/claude/projects",
				"**/claude/session-env",
				"**/claude/shell-snapshots",
				"**/claude/statsig",
				"**/claude/telemetry",
				"**/claude/todos",
				"**/claude/history.jsonl",
			},
		},
	},
}
