local config = {
  animate = { enabled = true },
  bigfile = { enabled = true },
  dashboard = { enabled = false },
  dim = { enabled = true },
  explorer = { enabled = true, replace_netrw = true },
  image = { enabled = true },
  indent = { enabled = true },
  input = { enabled = true },
  layout = { enabled = true },
  notifier = { enabled = true },
  quickfile = { enabled = true },
  scope = { enabled = true },
  scratch = { enabled = true },
  scroll = { enabled = true },
  statuscolumn = { enabled = true },
  terminal = { enabled = true },
  toggle = { enabled = true },
  words = { enabled = false },
  zen = { enabled = true },

  picker = {
    sources = {
      files = {
        hidden = true,
        ignored = true,
        win = {
          input = {
            keys = {
              ["<S-h>"] = "toggle_hidden",
              ["<S-i>"] = "toggle_ignored",
              ["<S-f>"] = "toggle_follow",
              ["<C-y>"] = { "yazi_copy_relative_path", mode = { "n", "i" } },
            },
          },
        },
        exclude = {
          "**/.git/*",
          "**/node_modules/*",
          "**/.yarn/cache/*",
          "**/.yarn/install*",
          "**/.yarn/releases/*",
          "**/.pnpm-store/*",
          "**/.idea/*",
          "**/.DS_Store",
          "build/*",
          "coverage/*",
          "dist/*",
          "hodor-types/*",
          "**/target/*",
          "**/public/*",
          "**/digest*.txt",
          "**/.node-gyp/**",
          "**/claude/debug",
          "**/claude/file-history",
          "**/claude/plans",
          "**/claude/plugins",
          "**/claude/projects",
          "**/claude/session-env",
          "**/claude/shell-snapshots",
          "**/claude/statsig",
          "**/claude/telemetry",
          "**/claude/todos",
          "**/claude/history.jsonl",
        },
      },
      grep = {
        hidden = true,
        ignored = true,
        win = {
          input = {
            keys = {
              ["<S-h>"] = "toggle_hidden",
              ["<S-i>"] = "toggle_ignored",
              ["<S-f>"] = "toggle_follow",
            },
          },
        },
        exclude = {
          "**/.git/*",
          "**/node_modules/*",
          "**/.yarn/cache/*",
          "**/.yarn/install*",
          "**/.yarn/releases/*",
          "**/.pnpm-store/*",
          "**/.venv/*",
          "**/.idea/*",
          "**/.DS_Store",
          "**/yarn.lock",
          "build*/*",
          "coverage/*",
          "dist/*",
          "certificates/*",
          "hodor-types/*",
          "**/target/*",
          "**/public/*",
          "**/digest*.txt",
          "**/.node-gyp/**",
          "**/claude/debug",
          "**/claude/file-history",
          "**/claude/plans",
          "**/claude/plugins",
          "**/claude/projects",
          "**/claude/session-env",
          "**/claude/shell-snapshots",
          "**/claude/statsig",
          "**/claude/telemetry",
          "**/claude/todos",
          "**/claude/history.jsonl",
        },
      },
      grep_buffers = {},
      explorer = {
        hidden = true,
        ignored = true,
        supports_live = true,
        auto_close = true,
        diagnostics = true,
        diagnostics_open = false,
        focus = "list",
        follow_file = true,
        git_status = true,
        git_status_open = false,
        git_untracked = true,
        jump = { close = true },
        tree = true,
        watch = true,
        exclude = {
          ".git",
          ".yarn/cache/**",
          ".yarn/install/**",
          ".yarn/install*",
          ".yarn/releases/**",
          ".pnpm-store",
          ".venv",
          ".DS_Store",
          "**/.node-gyp/**",
          "**/claude/debug",
          "**/claude/file-history",
          "**/claude/plans",
          "**/claude/plugins",
          "**/claude/projects",
          "**/claude/session-env",
          "**/claude/shell-snapshots",
          "**/claude/statsig",
          "**/claude/telemetry",
          "**/claude/todos",
          "**/claude/history.jsonl",
        },
      },
    },
  },
}

return {
  "snacks.nvim",
  after = function()
    local Snacks = require("snacks")
    Snacks.setup(config)
  end,
}
